### PR TITLE
Extract configs

### PR DESCRIPTION
**Pull request by cagdassalur**
Making it possible to set configs in the users own sh files(or in their `sketchybarrc`) so they don't have to modify plugin files

I had to dynamically create a string in `config.sh`, something like `key1=val1 key2=val2` so we can have the `script` attribute set up like `key1=val1 key2=val2 ~/path/to/script.sh` since sketchybar runs the scripts in a different process that doesn't have the environment variables from `sketchybarrc`.

Also not sure about the naming, feel free to make suggestions

### CODE REVIEW

**Comment by crissNb** [comment]
I definitely like the idea of exposing the config variables to more accessible space. Although, I'm not sure how easy it would be to navigate between different variables when they are all written in sketchybarrc in no particular order (especially when the user wants to change more than just one config).

Something that I'm thinking of is to have some sort of a precreated `userconfig.sh` that is organised and shows all the available variables to tweak (and their default values). All of these values can be commented to use the default values.
The idea is that the user can just make a copy of this file and uncomment + modify the variables they would like to change.

**Comment by cagdassalur** [comment]
That would be better, main benefit is being able to see all the options and their descriptions (with the default values) right there in the script, instead of digging readme.md or source, I'll add that in the pr. I'm not sure if i can give good descriptions though, i'll just copy existing ones and leave other alone.

**Comment by cagdassalur** [comment]
@crissNb how does it look now?

**Comment by cagdassalur** [comment]
I was thinking maybe namespacing the `USER_CONFIG` var and documenting it so user can specify where they want to place the config file, but idk

**Comment by crissNb** [comment]
I think we can have the `userconfig.sh` in `~/.config/sketchybar` at the moment, but it might be a better choice to have the userconfig in dynamic island folder so everything is organized in just one place. Although having it in `~/.config/sketchybar` definitely makes it more accessible...
I'll merge this PR for now, as I don't think the exact location of the userconfig.sh matters too much in terms of usability anyway.

**Pull request merged**
